# Generated by Django 4.1.5 on 2023-01-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='Route id')),
                ('departure_time', models.DateTimeField(verbose_name='Departure time')),
                ('return_time', models.DateTimeField(verbose_name='Return time')),
                ('departure_station_id', models.CharField(max_length=100, verbose_name='Departure station id')),
                ('departure_station_name', models.CharField(max_length=600, verbose_name='Departure station name')),
                ('return_station_id', models.CharField(max_length=100, verbose_name='Return station id')),
                ('return_station_name', models.CharField(max_length=600, verbose_name='Return station name')),
                ('covered_distance', models.CharField(max_length=10, verbose_name='Covered distance (m)')),
                ('duration', models.CharField(max_length=10, verbose_name='Duration (sec)')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('f_id', models.CharField(max_length=16, unique=True, verbose_name='Route id')),
                ('station_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='Route id')),
                ('name_fin', models.CharField(max_length=200, verbose_name='Name fin')),
                ('name_swd', models.CharField(max_length=200, verbose_name='Name swd')),
                ('name_eng', models.CharField(max_length=200, verbose_name='Name eng')),
                ('address_fin', models.CharField(max_length=300, verbose_name='Osoite fin')),
                ('address_swd', models.CharField(max_length=300, verbose_name='Adress swd')),
                ('city_fin', models.CharField(max_length=100, verbose_name='Kaupunki fin')),
                ('city_swd', models.CharField(max_length=100, verbose_name='Stad swd')),
                ('operator', models.CharField(max_length=200, verbose_name='Operaattor')),
                ('capacity', models.CharField(max_length=10, verbose_name='Kapasiteet')),
                ('coord_x', models.CharField(max_length=30, verbose_name='X')),
                ('coord_y', models.CharField(max_length=30, verbose_name='Y')),
            ],
        ),
    ]
