# Generated by Django 4.1.5 on 2023-01-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MistakesRoute',
            fields=[
                ('mistake_route_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='Mistake route id')),
                ('info_line', models.CharField(max_length=600, verbose_name='Info line')),
            ],
        ),
        migrations.CreateModel(
            name='MistakesStation',
            fields=[
                ('mistake_station_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='Mistake Station id')),
                ('info_line', models.CharField(max_length=600, verbose_name='Info line')),
            ],
        ),
        migrations.AlterField(
            model_name='station',
            name='f_id',
            field=models.CharField(max_length=16, unique=True, verbose_name='Station id'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='Station id'),
        ),
    ]
