# Generated by Django 4.1.5 on 2023-01-22 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mistakesroute_mistakesstation_alter_station_f_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='departure_station_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.station'),
        ),
    ]
