# Generated by Django 4.1.5 on 2023-01-22 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_route_departure_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='departure_station_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Departure_station_fk', to='main.station'),
        ),
        migrations.AlterField(
            model_name='route',
            name='return_station_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Return_station_fk', to='main.station'),
        ),
    ]
