# Generated by Django 4.1.5 on 2023-01-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_route_departure_station_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='covered_distance',
            field=models.IntegerField(max_length=10, verbose_name='Covered distance (m)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.IntegerField(max_length=10, verbose_name='Duration (sec)'),
        ),
        migrations.AlterField(
            model_name='station',
            name='capacity',
            field=models.IntegerField(max_length=10, verbose_name='Kapasiteet'),
        ),
    ]
