# Generated by Django 4.1.5 on 2023-01-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_route_covered_distance_alter_route_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='covered_distance',
            field=models.FloatField(verbose_name='Covered distance (m)'),
        ),
    ]
