# Generated by Django 4.1.5 on 2023-01-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_route_covered_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='covered_distance_km',
            field=models.FloatField(default='1', verbose_name='Covered distance (km)'),
        ),
        migrations.AddField(
            model_name='route',
            name='duration_min',
            field=models.FloatField(default='1', verbose_name='Duration (min)'),
        ),
    ]
